<div class="flex flex-col space-y-2">

    <p class="section-title">
        The Future of ICFC
    </p> 

    <p class="sub-header">
        Real Club Management
    </p>



    <p>
        ICFC allows us to expand our focus on true football club governance, ensuring supporters have their voice heard within their club community.
   </p>

    <p>Upon successful completion of our second decentralisation we will begin the process to purchase a UK football club within the professional English football league pyramid.</p>
    
    <p>We will showcase the unique abilities of the SNS governance procedure provided by the Internet Computer through the popular medium of showcasing the running of a football club through a TV show.</p>




    <p class="small-header">ICFC DAO & Sub-DAO Governance Model</p>

    <p>
        ICFC Parent DAO Responsibilities
    </p>
    <p>
        ICFC serves as the parent DAO, maintaining overarching control and providing resources to sub-DAOs. 
    </p>

    <p>
        Key responsibilities include: 
    </p>
    <ul>
        <li><b>Club Acquisitions: </b>Allocating capital raised to purchase clubs.</li>
        <li><b>Governance Frameworks: </b>Providing standardised smart contracts and voting structures for clubs.</li>
        <li><b>Liquidity Support: </b>Managing token liquidity pools.</li>
        <li><b>Meta-Governance: </b>Proposing high-level strategies that impact the entire ecosystem.</li>
        <li><b>Building Reserves: </b>Strengthening financial resilience and treasury stability via on-chain mechanisms.</li>
    </ul>

    <p class="text-xl cta-text">Sub-DAOs (Club-Level Governance)</p>

    <p>
        Each football club acquired by ICFC becomes a sub-DAO, issuing its own governance tokens. 
    </p>

    <p>
        These sub-DAOs:
    </p>

    <ul>
        <li>
            <b>Issue Governance Tokens</b> that provide voting rights on club decisions.
        </li>
        <li>
            <b>Manage a Club Treasury</b> funded by matchday revenue, sponsorships and merchandise sales.
        </li>
        <li>
            <b>Implement On-Chain Proposals</b> for hiring managers, player scouting & transfers, infrastructure investment and sponsorships.
        </li>
    </ul>

    <p>
        Example Governance Proposals: 
    </p>
    <ul>
        <li>Hiring & firing managers.</li>
        <li>Add / Remove player captaincy of club.</li>
        <li>Adding / Removing players from the scout list.</li>
        <li>Player signings & transfers.</li>
        <li>Youth academy and infrastructure funding.</li>
        <li>Sponsorship deal approvals.</li>
        <li>Club branding and marketing decisions. </li>
    </ul>

    <p>
        By using blockchain-based governance, ICFC empowers fans and stakeholders to participate in club decisions, 
        from hiring managers to scouting players through a tokenised voting system, running 100% on a decentralised blockchain.
    </p>
    <p>
        All tokens received are locked for six months, except for historic neuron tokens, which remain locked for two years - after which fans can begin dissolving their tokens.

Every year, a larger number of tokens is minted than in the previous year, ensuring that ownership primarily rests with recent attendees while earlier participation gradually carries less weight.

    </p>


Fan Profile
Each fan can create a profile that will track their attendance, engagement and overall token balances, giving an indication of how much of a die hard supporter they are. 

Fans can build a watchlist of players within our scouting network to keep track of people they are interested in signing. Fans will have access to videos that are uploaded along with available statistical performance on their performance. 

Fans of clubs that have been purchased by ICFC will be able to see the following club related information from the fan dashboard:
The percentage of voting power that is in the hands of the fans. This will give them confidence, knowing they are in control of their club. 
The revenue generated by their club in key areas such as ticket sales, merchandise sales and podcast revenue. 

Within the fan dashboard, fans will be able to: 
Add & remove a player to the club’s transfer list.
Add & remove a player to the club’s loan list.
Add & remove a player to the club’s scout list.
Add & remove the captaincy.
Create a player contract.
Renegotiate a player contract. 
Terminate a player contract. 
Propose facility upgrades.
Vote on club sponsorship by sponsorship categories. 
Manage sponsorship categories (Shirts/Pitchside etc).
General fan motions. 

Attendance-Based Decentralisation
Fans who physically attend matches & events earn governance tokens, ensuring voting power remains with the most engaged supporters. Long term supporters of clubs that are purchased will be invited to attend in person events, where they’ll be rewarded with a Historic Supporter Neuron. This will ensure that fans are well-equipped to ensure they know how to govern their club.

The ICFC DAO will retain a small stake and minor voting power (10%) in every club purchased. This ensures long-term stability, strategic alignment and responsible decentralisation across all sub-DAO by:
Preventing governance deadlocks or manipulation by bad actors.
Ensuring clubs remain aligned with ICFC’s broader mission.
ICFC neuron holders get a say in all clubs via the Guardian DAO’s collective voting stake.

All tokens acquired by the ICFC DAO to act as guardian will remain staked, indefinitely. 
ICFC’s innovative governance model is powered by a bespoke decentralisation platform that forms the backbone of our sub-DAO ecosystem. This platform is purpose-built to empower football clubs by embedding fan influence directly into every operational decision. By using the platform’s advanced, real-time capabilities, sub-DAOs can operate autonomously, ensuring that clubs are always aligned with the collective will of their supporters.
The platform enables swift translation of fan input into actionable governance and operational decisions. This ensures that clubs not only remain agile and responsive but also maintain continuous, efficient management, paving the way for sustained success and a dynamic, fan-led future in football.

Sub-DAO Token Split

The sub-DAO token split will be as follows: 
Historic Supporters: 25%
Season 1 Supporters: 25%
ICFC: 10%
Club Treasury (For club events and player social media promotion): 40%
I need to add more about how this inflationary tokenomics will work season by season,.


ICFC isn’t just a revolution in football ownership, it’s the catalyst that will propel the Internet Computer into mainstream adoption. 

Think of Wrexham’s Hollywood-backed resurgence - The ICFC DAO will merge football, entertainment & blockchain into a new medium where fans truly engage with their football club. This new medium will heavily feature the capabilities of the ICP blockchain (internetcomputer.org), enabling it to become a household name among everyday people.

ICFC will empower fans to own and have their say in club decisions. This new ownership structure will increase global club engagement through content related to real time decisions fans will make.

ICFC will be funded through the building of a strategic bitcoin reserve, used to purchase football clubs and integrate them with the ICFC club management app. A swap will occur throughout April 2025, if successful, decentralising 25% of the ICFC platform. 
ICFC operates as a Decentralised Autonomous Organisation (DAO) with a structured financial model:
The DAO will hold cryptocurrency balance of Bitcoin (ckBTC), ICP and ICFC tokens along with any user ICRC token assets deposited into our ecosystem for our range of football based applications.
Waterway Labs holds VP Control over ICFC to ensure effective software delivery, enhance treasury balances, and execute strategic growth initiatives.
Waterway Labs will legally own any football clubs acquired and will be responsible for generating profits and reinvesting back into club development.
The Club DAO will oversee player decisions, managerial appointments, and facility upgrades, ensuring that critical football-related operations remain decentralised and community-driven.
This ensures governance is shifted to the local fanbase. Unlike a fully open decentralisation sale, this process prioritises attendance-based decentralisation, where active match-going supporters have the opportunity to participate in club governance. 

Fans who purchase tickets will receive fan Sis it caub-DAO tokens as part of the transaction. These tokens represent governance rights within the club’s decentralised structure, reinforcing a system where committed supporters, those who attend and engage with the club, play a key role in decision-making. 

This also ensures that power isn’t distributed anonymously or speculatively and instead aligns with the club’s most engaged and invested fans. 

Over time, this framework builds a community-driven governance model, where those who contribute to the club’s success on and off the pitch have a say in its future. 

These fan based decentralisation sales will be run through the ICFC website, with tokens only purchasable through attending club matches & events.

To enhance and streamline this model, ICFC is exploring a strategic partnership with consultants who work directly with football clubs. This collaboration would facilitate the development of an automated system designed to handle the acquisition, management, and decentralisation process, ensuring a seamless transition of governance to the fans. 

For many club owners, selling a club isn’t just a financial transaction, it’s about safeguarding their legacy and ensuring the long-term success of the club. Community-led solutions like ICFC’s decentralised governance model offer an attractive pathway for these owners, providing a future where clubs remain deeply connected to their supporters, rather than being subject to short-term commercial interests. 





Sub-DAO Token Distribution
Governance tokens will be issued through:
Attendance-Based Minting: Tickets verified on-chain (QR codes, NFC, mobile wallets) to reward match attendees. 
Event & Social Media Engagement: Fans participating in events, training sessions or online campaigns earn tokens. 
Player & Scouting Rewards: Players and scouts receive tokens for contributing to club development. 

25 million ICFC tokens will be distributed among sale participants through five events, held every six months. Participants can log into the ICFC platform to track the dissolution of their ICFC neurons, confirming the amount that becomes liquid.
Fans who stake their sub-DAO tokens will earn maturity interest as a reward for keeping their neurons active. This incentive not only encourages long-term commitment and network stability but also provides a tangible benefit for fans who choose to maintain their stake, rather than dissolving their neurons prematurely.


Long-Term Viability
Token Lockup: Prevents rapid sell-offs, stabilising the token economy. In addition, our innovative platform enhances transparency by providing real-time visibility into the token lifecycle through a unique display of dissolving neurons. This feature allows users to monitor the gradual unlocking process and understand exactly how and when tokens become available. By visualising the dissolution of neurons, stakeholders gain valuable insights into liquidity trends and token flow, which reinforces confidence in the stability and integrity of the ecosystem.
Engagement-Driven Growth: Fans and players benefit directly from ecosystem success. 
Shared Success: Club-generated revenue benefits token holders. 



Diversified Revenue Streams
ICFC ensure long-term financial stability through:
Matchday Earnings: Ticket sales and stadium revenue.
Merchandise & Sponsorships: Attracting bands interested in community-driven teams. 
Scouting Network Services: Selling scouting data to other clubs. 
Event Hosting: Renting out stadium spaces for additional income. 

Revenue Allocation & Club Independence Statement
Match Day Revenue:
All earnings generated on match days are the sole revenue of the individual clubs. This income is dedicated exclusively to the club’s operations, development, and community activities. No portion of match day revenue will be diverted into any communal fund.







    <p class="sub-header">
        The DAO Documentary
    </p>

    <p>Our plan for mass adoption using a 'Welcome to Wrexham' style show.</p>

    <p class="sub-header">
        Merchandise
    </p>

    <p class="sub-header">
        Fan Podcasts
    </p>

    ICFC Sports Writer & Fan Podcast Accounts: Community-Driven Football Media
ICFC introduces a community-powered sports media platform, allowing football writers and fan podcasters to create, share, and monetise their content. 
For just 1 ICP, users can set up a verified Sports Writer or Fan Podcast account on icfc.app, unlocking tools to build their audience, publish exclusive articles, and host podcasts.
This system fosters a more organic, fan-driven football media landscape, where passionate supporters can connect through match analysis, tactical breakdowns, transfer news, and in-depth discussions. Fans can subscribe to their favourite writers and podcasters through a subscription-based model, offering exclusive access to premium content, bonus episodes, behind-the-scenes insights, or interactive Q&A sessions.
By decentralising football journalism and fan-driven content, ICFC provides a platform where engagement, insight, and storytelling thrive, giving supporters direct access to the most authentic voices in football media - created by the fans, for the fans.


    <p class="sub-header">
        Sports Writers
    </p>

    <p class="sub-header">AI Data Expansion</p>


</div>